apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xtny
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0054-tenant/tkrw-pr712-0075-0054-app/devfile-sample-xtny@sha256:867b1955062e9c96c834d399190c619135fb06ba7fde20a3b3d5a8745d7ad098
        name: my-nodejs
        resources: {}
status: {}
